steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/hello:$COMMIT_SHA",
        "-f",
        "server-side/Dockerfile",
        ".",
      ]
  # Push the container image to Container Registry in asia-northeast1
  - name: "gcr.io/cloud-builders/docker"
    args: [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/hello:$COMMIT_SHA",
      ] # asia-northeast1-docker.pkg.dev/$PROJECT_ID/hello:$COMMIT_SHAにコンテナをpushする
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "hello"
      - "--image"
      - "gcr.io/$PROJECT_ID/hello:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"
      - "--set-env-vars"
      - "USER_NAME=tarou,USER_AGE=20,USER_ADDRESS=tokyo" # --set-env-varsの後に複数の環境変数を指定可（これがCloudRunにセットされる）
images:
  - "gcr.io/$PROJECT_ID/hello:$COMMIT_SHA"
